# Generated by Django 3.2 on 2024-05-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The Group s this user belongs to', related_name='extenduser_groups', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific Permissions for this user', related_name='extenduser_permissions', to='auth.Permission'),
        ),
    ]
